#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 1. Go into the client folder (CRITICAL STEP)
cd client

# 2. Run the checks
echo "🔍 Running Pre-Commit Checks..."
npx lint-staged

# 3. Check Types
echo "TypeScript Check..."
npx tsc --noEmit